server:
  #TODO
  port: 8091

# dynamic thread pool config
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# log
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
